/**
 * Lead Creation Service - Complete Lead Creation Orchestration
 *
 * This service orchestrates the complete lead creation flow:
 * 1. lead_code auto-generated by PostgreSQL trigger (L-XXXXXX format)
 * 2. Assign to appropriate sales representative
 * 3. Create lead in database with all computed fields
 *
 * Used by POST /api/v1/crm/leads endpoint to provide a single,
 * transactional operation for lead creation with automatic qualification.
 *
 * @module lib/services/crm/lead-creation.service
 */

import { prisma } from "@/lib/prisma";
import { LeadRepository } from "@/lib/repositories/crm/lead.repository";
import { LeadAssignmentService } from "./lead-assignment.service";
import { CountryService } from "./country.service";
import { ValidationError } from "@/lib/core/errors";
import { sendNotification } from "@/lib/notifications";
import { logger } from "@/lib/logger";
import { URLS } from "@/lib/config/urls.config";
import type { CreateLeadInput } from "@/lib/validators/crm/lead.validators";
import type { crm_leads } from "@prisma/client";

/**
 * Result of lead creation orchestration
 *
 * Includes the created lead record plus computed scoring and assignment details.
 */
export interface LeadCreationResult {
  lead: crm_leads;
  assignment: {
    assigned_to: string | null;
    assignment_reason: string;
  };
}

/**
 * Eligible employee structure for assignment
 * Matches adm_members table structure
 */
interface EligibleEmployee {
  id: string;
  first_name: string;
  last_name: string | null;
  email: string;
  title: string;
  status: string;
}

/**
 * Lead Creation Service
 *
 * Orchestrates complete lead creation flow with
 * priority determination and sales rep assignment.
 *
 * @example
 * ```typescript
 * const service = new LeadCreationService();
 * const result = await service.createLead(
 *   {
 *     email: "ceo@bigfleet.ae",
 *     fleet_size: "500+",
 *     country_code: "AE",
 *     message: "We need fleet management...",
 *     source: "website"
 *   },
 *   "tenant-uuid",
 *   "user-uuid"
 * );
 * // Returns: { lead, assignment }
 * ```
 */
export class LeadCreationService {
  private leadRepo: LeadRepository;
  private assignmentService: LeadAssignmentService;
  private countryService: CountryService;

  constructor() {
    this.leadRepo = new LeadRepository(prisma);
    this.assignmentService = new LeadAssignmentService();
    this.countryService = new CountryService();
  }

  /**
   * Create lead with complete orchestration
   *
   * Orchestrates all steps of lead creation:
   * - Generate unique lead code
   * - Calculate fit and engagement scores
   * - Determine qualification score and lead stage
   * - Calculate priority (low/medium/high/urgent)
   * - Fetch active employees
   * - Assign to appropriate sales rep
   * - Create lead in database
   *
   * @param input - Validated lead creation input
   * @param tenantId - Tenant UUID (FleetCore division for data isolation)
   * @param createdBy - Employee UUID who created lead (optional, for internal leads)
   * @returns Complete lead creation result
   *
   * @throws Error if lead code generation fails
   * @throws Error if scoring configuration not found
   * @throws Error if assignment configuration not found
   * @throws Error if database create fails
   *
   * @example
   * ```typescript
   * const result = await service.createLead(
   *   { email: "test@example.com", source: "website" },
   *   "tenant-123",
   *   "user-456"
   * );
   *
   * // result.lead.lead_code: "L-R7M8J6" (PostgreSQL trigger)
   * // result.lead.status: "new"
   * // result.assignment.assigned_to: "emp-uuid"
   * ```
   */
  async createLead(
    input: CreateLeadInput,
    tenantId: string,
    createdBy?: string
  ): Promise<LeadCreationResult> {
    // STEP 0: GDPR validation (before any processing)
    if (input.country_code) {
      const isGdprCountry = await this.countryService.isGdprCountry(
        input.country_code
      );

      if (isGdprCountry) {
        // EU/EEA country → GDPR consent required
        if (!input.gdpr_consent) {
          throw new ValidationError(
            `GDPR consent required for EU/EEA countries (country: ${input.country_code})`
          );
        }

        if (!input.consent_ip) {
          throw new ValidationError(
            "Consent IP address required for GDPR compliance"
          );
        }
      }
    }

    // STEP 1: lead_code auto-generated by PostgreSQL trigger (trg_set_lead_code)
    // Format: L-XXXXXX (random alphanumeric, no sequential numbers for security)

    // STEP 2: Fetch active members for assignment
    const activeEmployees = await prisma.adm_members.findMany({
      where: {
        status: "active",
        deleted_at: null,
      },
      select: {
        id: true,
        first_name: true,
        last_name: true,
        email: true,
        role: true,
        status: true,
      },
    });

    // STEP 3: Assign to sales rep
    const assignment = await this.assignmentService.assignToSalesRep(
      {
        fleet_size: input.fleet_size ?? null,
        country_code: input.country_code ?? null,
      },
      activeEmployees as unknown as EligibleEmployee[]
    );

    // STEP 3.5: Check expansion opportunity (non-operational countries)
    let enrichedMetadata = input.metadata || {};

    if (input.country_code) {
      const isOperational = await this.countryService.isOperational(
        input.country_code
      );

      if (!isOperational) {
        // FleetCore not yet available → Mark as expansion opportunity
        enrichedMetadata = {
          ...enrichedMetadata,
          expansion_opportunity: true,
          expansion_country: input.country_code,
          expansion_detected_at: new Date().toISOString(),
        };
      }
    }

    // STEP 4: Create lead in database
    // Use provided priority/assigned_to if given, otherwise use defaults
    const finalPriority = input.priority ?? "medium";
    const finalAssignedTo =
      input.assigned_to_id ?? assignment.assigned_to ?? null;

    const leadData = {
      // lead_code: auto-generated by PostgreSQL trigger (trg_set_lead_code)
      email: input.email,
      first_name: input.first_name,
      last_name: input.last_name,
      company_name: input.company_name ?? null,
      phone: input.phone ?? null,
      fleet_size: input.fleet_size ?? null,
      country_code: input.country_code ?? null,
      city: input.city ?? null,
      website_url: input.website_url ?? null,
      current_software: input.current_software ?? null,
      message: input.message ?? null,
      source: input.source ?? null,
      utm_source: input.utm_source ?? null,
      utm_medium: input.utm_medium ?? null,
      utm_campaign: input.utm_campaign ?? null,

      // Assignment (use provided or auto-assigned)
      assigned_to: finalAssignedTo,

      // Priority (use provided or auto-calculated)
      priority: finalPriority,

      // Status
      status: "new",

      // GDPR fields (only for EU/EEA countries)
      gdpr_consent: input.gdpr_consent ?? null,
      consent_at: input.gdpr_consent ? new Date() : null,
      consent_ip: input.consent_ip ?? null,

      // Metadata (enriched with expansion flag if applicable)
      metadata: enrichedMetadata,
    };

    const lead = await this.leadRepo.create(
      leadData,
      createdBy ?? "",
      tenantId
    );

    // STEP 5: Send notification to assigned sales rep (if assigned)
    if (assignment.assigned_to) {
      // Find the assigned employee to get their email and name
      const assignedEmployee = activeEmployees.find(
        (emp) => emp.id === assignment.assigned_to
      );

      if (assignedEmployee) {
        const leadName =
          [input.first_name, input.last_name].filter(Boolean).join(" ") ||
          input.email.split("@")[0];

        try {
          const notificationResult = await sendNotification(
            "crm.sales.assignment",
            assignedEmployee.email,
            {
              employee_name: assignedEmployee.first_name ?? "",
              lead_name: leadName,
              company_name: input.company_name || "N/A",
              priority: finalPriority,
              fleet_size: input.fleet_size || "N/A",
              country_code: input.country_code || "N/A",
              lead_detail_url: `${URLS.app}/crm/leads/${lead.id}`,
            },
            {
              leadId: lead.id,
              tenantId,
              idempotencyKey: `sales_rep_assignment_${lead.id}`,
            }
          );

          logger.info(
            {
              leadId: lead.id,
              leadCode: lead.lead_code,
              assignedTo: assignedEmployee.email,
              notificationQueued: notificationResult.success,
              queueId: notificationResult.queueId,
            },
            "[Lead Creation] Sales rep assignment notification queued"
          );
        } catch (notificationError) {
          // Log error but don't fail lead creation
          logger.error(
            {
              leadId: lead.id,
              error:
                notificationError instanceof Error
                  ? notificationError.message
                  : "Unknown",
            },
            "[Lead Creation] Failed to queue sales rep assignment notification"
          );
        }
      }
    }

    return {
      lead,
      assignment: {
        assigned_to: assignment.assigned_to,
        assignment_reason: assignment.assignment_reason,
      },
    };
  }
}
